In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## define the vocabulary size

voc_size = 10000


In [6]:
## One Hot Representation

one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[5553, 8738, 769, 8067],
 [5553, 8738, 769, 2429],
 [5553, 5953, 769, 9890],
 [9705, 9182, 1839, 4285, 855],
 [9705, 9182, 1839, 4285, 7396],
 [941, 5553, 1084, 769, 6401],
 [253, 4560, 4249, 4285]]

In [7]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [8]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5553 8738  769 8067]
 [   0    0    0    0 5553 8738  769 2429]
 [   0    0    0    0 5553 5953  769 9890]
 [   0    0    0 9705 9182 1839 4285  855]
 [   0    0    0 9705 9182 1839 4285 7396]
 [   0    0    0  941 5553 1084  769 6401]
 [   0    0    0    0  253 4560 4249 4285]]


In [11]:
## feature representation

dim=10


In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

c:\Users\humai\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5553, 8738,  769, 8067], dtype=int32)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 453ms/step


array([[[ 2.86086835e-02,  4.87218015e-02,  1.66130550e-02,
          3.99195664e-02, -1.56225562e-02, -1.11871473e-02,
          2.60459892e-02, -3.32718268e-02, -2.86141783e-03,
         -2.65823603e-02],
        [ 2.86086835e-02,  4.87218015e-02,  1.66130550e-02,
          3.99195664e-02, -1.56225562e-02, -1.11871473e-02,
          2.60459892e-02, -3.32718268e-02, -2.86141783e-03,
         -2.65823603e-02],
        [ 2.86086835e-02,  4.87218015e-02,  1.66130550e-02,
          3.99195664e-02, -1.56225562e-02, -1.11871473e-02,
          2.60459892e-02, -3.32718268e-02, -2.86141783e-03,
         -2.65823603e-02],
        [ 2.86086835e-02,  4.87218015e-02,  1.66130550e-02,
          3.99195664e-02, -1.56225562e-02, -1.11871473e-02,
          2.60459892e-02, -3.32718268e-02, -2.86141783e-03,
         -2.65823603e-02],
        [ 2.00391151e-02,  2.57903002e-02,  1.60847642e-02,
          1.02491491e-02, -4.27577756e-02, -4.64200750e-02,
         -2.05753800e-02, -1.66975632e-02,  3.322582